env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
rust:
  - stable
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - rustup component add rustfmt clippy
jobs:
  include:
    - script: scripts/clippy
      os: linux
    - script: scripts/clippy
      os: osx
    - script: scripts/tests
      os: linux
    - script: scripts/tests
      os: osx
before_cache:
 - cargo prune
